/*

 LEVEL_ANIM_VCONV.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 7

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define level_anim_vconvBank 0

/* Super Gameboy palette 0 */
#define level_anim_vconvSGBPal0c0 6076
#define level_anim_vconvSGBPal0c1 8935
#define level_anim_vconvSGBPal0c2 6596
#define level_anim_vconvSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define level_anim_vconvSGBPal1c0 6076
#define level_anim_vconvSGBPal1c1 8935
#define level_anim_vconvSGBPal1c2 6596
#define level_anim_vconvSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define level_anim_vconvSGBPal2c0 6076
#define level_anim_vconvSGBPal2c1 8935
#define level_anim_vconvSGBPal2c2 6596
#define level_anim_vconvSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define level_anim_vconvSGBPal3c0 6076
#define level_anim_vconvSGBPal3c1 8935
#define level_anim_vconvSGBPal3c2 6596
#define level_anim_vconvSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define level_anim_vconvCGBPal0c0 31670
#define level_anim_vconvCGBPal0c1 32642
#define level_anim_vconvCGBPal0c2 24096
#define level_anim_vconvCGBPal0c3 0

/* Gameboy Color palette 1 */
#define level_anim_vconvCGBPal1c0 32767
#define level_anim_vconvCGBPal1c1 8479
#define level_anim_vconvCGBPal1c2 17
#define level_anim_vconvCGBPal1c3 0

/* Gameboy Color palette 2 */
#define level_anim_vconvCGBPal2c0 19458
#define level_anim_vconvCGBPal2c1 32767
#define level_anim_vconvCGBPal2c2 13741
#define level_anim_vconvCGBPal2c3 0

/* Gameboy Color palette 3 */
#define level_anim_vconvCGBPal3c0 19458
#define level_anim_vconvCGBPal3c1 14317
#define level_anim_vconvCGBPal3c2 3616
#define level_anim_vconvCGBPal3c3 0

/* Gameboy Color palette 4 */
#define level_anim_vconvCGBPal4c0 19458
#define level_anim_vconvCGBPal4c1 31411
#define level_anim_vconvCGBPal4c2 32102
#define level_anim_vconvCGBPal4c3 0

/* Gameboy Color palette 5 */
#define level_anim_vconvCGBPal5c0 19458
#define level_anim_vconvCGBPal5c1 29214
#define level_anim_vconvCGBPal5c2 3616
#define level_anim_vconvCGBPal5c3 0

/* Gameboy Color palette 6 */
#define level_anim_vconvCGBPal6c0 19458
#define level_anim_vconvCGBPal6c1 23254
#define level_anim_vconvCGBPal6c2 31
#define level_anim_vconvCGBPal6c3 0

/* Gameboy Color palette 7 */
#define level_anim_vconvCGBPal7c0 19458
#define level_anim_vconvCGBPal7c1 9887
#define level_anim_vconvCGBPal7c2 375
#define level_anim_vconvCGBPal7c3 0
/* CGBpalette entries. */
extern unsigned char level_anim_vconvCGB[];
/* Start of tile array. */
extern unsigned char level_anim_vconv[];

/* End of LEVEL_ANIM_VCONV.H */
