/*

 SRC/LEVEL1_PARALLAXTILES.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 511

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define level1_parallaxtilesBank 0

/* Super Gameboy palette 0 */
#define level1_parallaxtilesSGBPal0c0 6076
#define level1_parallaxtilesSGBPal0c1 8935
#define level1_parallaxtilesSGBPal0c2 6596
#define level1_parallaxtilesSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define level1_parallaxtilesSGBPal1c0 6076
#define level1_parallaxtilesSGBPal1c1 8935
#define level1_parallaxtilesSGBPal1c2 6596
#define level1_parallaxtilesSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define level1_parallaxtilesSGBPal2c0 6076
#define level1_parallaxtilesSGBPal2c1 8935
#define level1_parallaxtilesSGBPal2c2 6596
#define level1_parallaxtilesSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define level1_parallaxtilesSGBPal3c0 6076
#define level1_parallaxtilesSGBPal3c1 8935
#define level1_parallaxtilesSGBPal3c2 6596
#define level1_parallaxtilesSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define level1_parallaxtilesCGBPal0c0 19458
#define level1_parallaxtilesCGBPal0c1 31411
#define level1_parallaxtilesCGBPal0c2 32102
#define level1_parallaxtilesCGBPal0c3 0

/* Gameboy Color palette 1 */
#define level1_parallaxtilesCGBPal1c0 32767
#define level1_parallaxtilesCGBPal1c1 8479
#define level1_parallaxtilesCGBPal1c2 17
#define level1_parallaxtilesCGBPal1c3 0

/* Gameboy Color palette 2 */
#define level1_parallaxtilesCGBPal2c0 19458
#define level1_parallaxtilesCGBPal2c1 32767
#define level1_parallaxtilesCGBPal2c2 13741
#define level1_parallaxtilesCGBPal2c3 0

/* Gameboy Color palette 3 */
#define level1_parallaxtilesCGBPal3c0 19458
#define level1_parallaxtilesCGBPal3c1 14317
#define level1_parallaxtilesCGBPal3c2 3616
#define level1_parallaxtilesCGBPal3c3 0

/* Gameboy Color palette 4 */
#define level1_parallaxtilesCGBPal4c0 19458
#define level1_parallaxtilesCGBPal4c1 31411
#define level1_parallaxtilesCGBPal4c2 32102
#define level1_parallaxtilesCGBPal4c3 0

/* Gameboy Color palette 5 */
#define level1_parallaxtilesCGBPal5c0 19458
#define level1_parallaxtilesCGBPal5c1 29214
#define level1_parallaxtilesCGBPal5c2 3616
#define level1_parallaxtilesCGBPal5c3 0

/* Gameboy Color palette 6 */
#define level1_parallaxtilesCGBPal6c0 19458
#define level1_parallaxtilesCGBPal6c1 23254
#define level1_parallaxtilesCGBPal6c2 31
#define level1_parallaxtilesCGBPal6c3 0

/* Gameboy Color palette 7 */
#define level1_parallaxtilesCGBPal7c0 19458
#define level1_parallaxtilesCGBPal7c1 9887
#define level1_parallaxtilesCGBPal7c2 375
#define level1_parallaxtilesCGBPal7c3 0
/* CGBpalette entries. */
extern unsigned char level1_parallaxtilesCGB[];
/* Start of tile array. */
extern unsigned char level1_parallaxtiles[];

/* End of SRC/LEVEL1_PARALLAXTILES.H */
