/*

 LEVEL_ANIM_HCONV.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 7

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define level_anim_hconvBank 0

/* Super Gameboy palette 0 */
#define level_anim_hconvSGBPal0c0 6076
#define level_anim_hconvSGBPal0c1 8935
#define level_anim_hconvSGBPal0c2 6596
#define level_anim_hconvSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define level_anim_hconvSGBPal1c0 6076
#define level_anim_hconvSGBPal1c1 8935
#define level_anim_hconvSGBPal1c2 6596
#define level_anim_hconvSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define level_anim_hconvSGBPal2c0 6076
#define level_anim_hconvSGBPal2c1 8935
#define level_anim_hconvSGBPal2c2 6596
#define level_anim_hconvSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define level_anim_hconvSGBPal3c0 6076
#define level_anim_hconvSGBPal3c1 8935
#define level_anim_hconvSGBPal3c2 6596
#define level_anim_hconvSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define level_anim_hconvCGBPal0c0 31670
#define level_anim_hconvCGBPal0c1 32642
#define level_anim_hconvCGBPal0c2 24096
#define level_anim_hconvCGBPal0c3 0

/* Gameboy Color palette 1 */
#define level_anim_hconvCGBPal1c0 32767
#define level_anim_hconvCGBPal1c1 8479
#define level_anim_hconvCGBPal1c2 17
#define level_anim_hconvCGBPal1c3 0

/* Gameboy Color palette 2 */
#define level_anim_hconvCGBPal2c0 19458
#define level_anim_hconvCGBPal2c1 32767
#define level_anim_hconvCGBPal2c2 13741
#define level_anim_hconvCGBPal2c3 0

/* Gameboy Color palette 3 */
#define level_anim_hconvCGBPal3c0 19458
#define level_anim_hconvCGBPal3c1 14317
#define level_anim_hconvCGBPal3c2 3616
#define level_anim_hconvCGBPal3c3 0

/* Gameboy Color palette 4 */
#define level_anim_hconvCGBPal4c0 19458
#define level_anim_hconvCGBPal4c1 31411
#define level_anim_hconvCGBPal4c2 32102
#define level_anim_hconvCGBPal4c3 0

/* Gameboy Color palette 5 */
#define level_anim_hconvCGBPal5c0 19458
#define level_anim_hconvCGBPal5c1 29214
#define level_anim_hconvCGBPal5c2 3616
#define level_anim_hconvCGBPal5c3 0

/* Gameboy Color palette 6 */
#define level_anim_hconvCGBPal6c0 19458
#define level_anim_hconvCGBPal6c1 23254
#define level_anim_hconvCGBPal6c2 31
#define level_anim_hconvCGBPal6c3 0

/* Gameboy Color palette 7 */
#define level_anim_hconvCGBPal7c0 19458
#define level_anim_hconvCGBPal7c1 9887
#define level_anim_hconvCGBPal7c2 375
#define level_anim_hconvCGBPal7c3 0
/* CGBpalette entries. */
extern unsigned char level_anim_hconvCGB[];
/* Start of tile array. */
extern unsigned char level_anim_hconv[];

/* End of LEVEL_ANIM_HCONV.H */
