/*

 MAP_MENU_ANIM_SETTINGS.H

 Map Include File.

 Info:
   Section       : Map
   Bank          : 0
   Map size      : 12 x 10
   Tile set      : menu.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define map_menu_anim_settingsWidth 12
#define map_menu_anim_settingsHeight 10
#define map_menu_anim_settingsBank 0

extern unsigned char map_menu_anim_settings[];

/* End of MAP_MENU_ANIM_SETTINGS.H */
