/*

 MAP_MENU_ANIM_ASTEROID.B3.C

 Map Source File.

 Info:
   Section       : Map
   Bank          : 0
   Map size      : 3 x 12
   Tile set      : menu.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define map_menu_anim_asteroidWidth 3
#define map_menu_anim_asteroidHeight 12
#define map_menu_anim_asteroidBank 0

const unsigned  char map_menu_anim_asteroid[] =
{
  0xB3,0xB4,0xB5,0xB6,0xB7,0xB8,0xB9,0xBA,0xBB,0xBC,
  0xBD,0xBE,0xBF,0xC0,0xC1,0xC2,0xC3,0xC4,0xC5,0xC6,
  0xC7,0xC8,0xC9,0xCA,0xCB,0xCC,0xCD,0xBC,0xBD,0xBE,
  0xBF,0xC0,0xC1,0xC2,0xC3,0xC4
};

/* End of MAP_MENU_ANIM_ASTEROID.B3.C */
