/*

 MAP_LEVEL0.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 48 x 48
   Tile set      : level1.gbr
   Plane count   : 2 planes (16 bits)
   Plane order   : Planes are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define map_level0Width 48
#define map_level0Height 48
#define map_level0Bank 0

#define map_level0 map_level0PLN0
extern unsigned char map_level0PLN0[];
extern unsigned char map_level0PLN1[];

/* End of MAP_LEVEL0.H */
