/*

 MAP_LEVEL1.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 68 x 67
   Tile set      : level1.gbr
   Plane count   : 2 planes (16 bits)
   Plane order   : Planes are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define map_level1Width 68
#define map_level1Height 67
#define map_level1Bank 0

#define map_level1 map_level1PLN0
extern unsigned char map_level1PLN0[];
extern unsigned char map_level1PLN1[];

/* End of MAP_LEVEL1.H */
