/*

 MAP_MENU_ANIM_BALL.B3.C

 Map Source File.

 Info:
   Section       : Map
   Bank          : 0
   Map size      : 2 x 12
   Tile set      : menu.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define map_menu_anim_ballWidth 2
#define map_menu_anim_ballHeight 12
#define map_menu_anim_ballBank 0

const unsigned  char map_menu_anim_ball[] =
{
  0x89,0x8A,0x8B,0x8C,0x8D,0x8E,0x83,0x84,0x85,0x86,
  0x87,0x88,0x7D,0x7E,0x7F,0x80,0x81,0x82,0x83,0x84,
  0x85,0x86,0x87,0x88
};

/* End of MAP_MENU_ANIM_BALL.B3.C */
