/*

 MAP_LOADING.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : Loading.gbr
   Plane count   : 2 planes (16 bits)
   Plane order   : Planes are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define map_loadingWidth 20
#define map_loadingHeight 18
#define map_loadingBank 0

#define map_loading map_loadingPLN0
extern unsigned char map_loadingPLN0[];
extern unsigned char map_loadingPLN1[];

/* End of MAP_LOADING.H */
