/*

 MAP_PLOGO.H

 Map Include File.

 Info:
   Section       : Map
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : menu.gbr
   Plane count   : 2 planes (16 bits)
   Plane order   : Planes are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define map_plogoWidth 20
#define map_plogoHeight 18
#define map_plogoBank 0

#define map_plogo map_plogoPLN0
extern unsigned char map_plogoPLN0[];
extern unsigned char map_plogoPLN1[];

/* End of MAP_PLOGO.H */
