/*

 MAP_MENU_ANIM_BALL.H

 Map Include File.

 Info:
   Section       : Map
   Bank          : 0
   Map size      : 2 x 12
   Tile set      : menu.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define map_menu_anim_ballWidth 2
#define map_menu_anim_ballHeight 12
#define map_menu_anim_ballBank 0

extern unsigned char map_menu_anim_ball[];

/* End of MAP_MENU_ANIM_BALL.H */
