/*

 SRC/PLAYER.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 16 x 16
  Tiles                : 0 to 4

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define playerBank 0

/* Super Gameboy palette 0 */
#define playerSGBPal0c0 6076
#define playerSGBPal0c1 8935
#define playerSGBPal0c2 6596
#define playerSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define playerSGBPal1c0 6076
#define playerSGBPal1c1 8935
#define playerSGBPal1c2 6596
#define playerSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define playerSGBPal2c0 6076
#define playerSGBPal2c1 8935
#define playerSGBPal2c2 6596
#define playerSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define playerSGBPal3c0 6076
#define playerSGBPal3c1 8935
#define playerSGBPal3c2 6596
#define playerSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define playerCGBPal0c0 32767
#define playerCGBPal0c1 32767
#define playerCGBPal0c2 23254
#define playerCGBPal0c3 0

/* Gameboy Color palette 1 */
#define playerCGBPal1c0 16417
#define playerCGBPal1c1 1087
#define playerCGBPal1c2 82
#define playerCGBPal1c3 0

/* Gameboy Color palette 2 */
#define playerCGBPal2c0 16417
#define playerCGBPal2c1 9193
#define playerCGBPal2c2 1568
#define playerCGBPal2c3 0

/* Gameboy Color palette 3 */
#define playerCGBPal3c0 16417
#define playerCGBPal3c1 9213
#define playerCGBPal3c2 724
#define playerCGBPal3c3 0

/* Gameboy Color palette 4 */
#define playerCGBPal4c0 16417
#define playerCGBPal4c1 32521
#define playerCGBPal4c2 6142
#define playerCGBPal4c3 0

/* Gameboy Color palette 5 */
#define playerCGBPal5c0 16417
#define playerCGBPal5c1 32521
#define playerCGBPal5c2 1087
#define playerCGBPal5c3 0

/* Gameboy Color palette 6 */
#define playerCGBPal6c0 16417
#define playerCGBPal6c1 32521
#define playerCGBPal6c2 31839
#define playerCGBPal6c3 0

/* Gameboy Color palette 7 */
#define playerCGBPal7c0 17441
#define playerCGBPal7c1 32767
#define playerCGBPal7c2 223
#define playerCGBPal7c3 0
/* CGBpalette entries. */
extern unsigned char playerCGB[];
/* Start of tile array. */
extern unsigned char player[];

/* End of SRC/PLAYER.H */
