/*

 SRC/SPRITESHIP1.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 16 x 16
  Tiles                : 0 to 2

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define spriteship1Bank 0

/* Super Gameboy palette 0 */
#define spriteship1SGBPal0c0 6076
#define spriteship1SGBPal0c1 8935
#define spriteship1SGBPal0c2 6596
#define spriteship1SGBPal0c3 5344

/* Super Gameboy palette 1 */
#define spriteship1SGBPal1c0 6076
#define spriteship1SGBPal1c1 8935
#define spriteship1SGBPal1c2 6596
#define spriteship1SGBPal1c3 5344

/* Super Gameboy palette 2 */
#define spriteship1SGBPal2c0 6076
#define spriteship1SGBPal2c1 8935
#define spriteship1SGBPal2c2 6596
#define spriteship1SGBPal2c3 5344

/* Super Gameboy palette 3 */
#define spriteship1SGBPal3c0 6076
#define spriteship1SGBPal3c1 8935
#define spriteship1SGBPal3c2 6596
#define spriteship1SGBPal3c3 5344

/* Gameboy Color palette 0 */
#define spriteship1CGBPal0c0 16417
#define spriteship1CGBPal0c1 32521
#define spriteship1CGBPal0c2 31839
#define spriteship1CGBPal0c3 0

/* Gameboy Color palette 1 */
#define spriteship1CGBPal1c0 16417
#define spriteship1CGBPal1c1 32063
#define spriteship1CGBPal1c2 20502
#define spriteship1CGBPal1c3 0

/* Gameboy Color palette 2 */
#define spriteship1CGBPal2c0 16417
#define spriteship1CGBPal2c1 32521
#define spriteship1CGBPal2c2 6142
#define spriteship1CGBPal2c3 0

/* Gameboy Color palette 3 */
#define spriteship1CGBPal3c0 16417
#define spriteship1CGBPal3c1 9213
#define spriteship1CGBPal3c2 724
#define spriteship1CGBPal3c3 0

/* Gameboy Color palette 4 */
#define spriteship1CGBPal4c0 16417
#define spriteship1CGBPal4c1 32521
#define spriteship1CGBPal4c2 1087
#define spriteship1CGBPal4c3 0

/* Gameboy Color palette 5 */
#define spriteship1CGBPal5c0 16417
#define spriteship1CGBPal5c1 1087
#define spriteship1CGBPal5c2 82
#define spriteship1CGBPal5c3 0

/* Gameboy Color palette 6 */
#define spriteship1CGBPal6c0 16417
#define spriteship1CGBPal6c1 9193
#define spriteship1CGBPal6c2 1568
#define spriteship1CGBPal6c3 0

/* Gameboy Color palette 7 */
#define spriteship1CGBPal7c0 16417
#define spriteship1CGBPal7c1 32767
#define spriteship1CGBPal7c2 13741
#define spriteship1CGBPal7c3 0
/* CGBpalette entries. */
extern unsigned char spriteship1CGB[];
/* Start of tile array. */
extern unsigned char spriteship1[];

/* End of SRC/SPRITESHIP1.H */
