/*

 SRC/SPRITESHIP.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 16 x 16
  Tiles                : 0 to 3

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define spriteshipBank 0

/* Super Gameboy palette 0 */
#define spriteshipSGBPal0c0 6076
#define spriteshipSGBPal0c1 8935
#define spriteshipSGBPal0c2 6596
#define spriteshipSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define spriteshipSGBPal1c0 6076
#define spriteshipSGBPal1c1 8935
#define spriteshipSGBPal1c2 6596
#define spriteshipSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define spriteshipSGBPal2c0 6076
#define spriteshipSGBPal2c1 8935
#define spriteshipSGBPal2c2 6596
#define spriteshipSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define spriteshipSGBPal3c0 6076
#define spriteshipSGBPal3c1 8935
#define spriteshipSGBPal3c2 6596
#define spriteshipSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define spriteshipCGBPal0c0 16417
#define spriteshipCGBPal0c1 32521
#define spriteshipCGBPal0c2 31839
#define spriteshipCGBPal0c3 0

/* Gameboy Color palette 1 */
#define spriteshipCGBPal1c0 16417
#define spriteshipCGBPal1c1 32063
#define spriteshipCGBPal1c2 20502
#define spriteshipCGBPal1c3 0

/* Gameboy Color palette 2 */
#define spriteshipCGBPal2c0 16417
#define spriteshipCGBPal2c1 32521
#define spriteshipCGBPal2c2 6142
#define spriteshipCGBPal2c3 0

/* Gameboy Color palette 3 */
#define spriteshipCGBPal3c0 16417
#define spriteshipCGBPal3c1 9213
#define spriteshipCGBPal3c2 724
#define spriteshipCGBPal3c3 0

/* Gameboy Color palette 4 */
#define spriteshipCGBPal4c0 16417
#define spriteshipCGBPal4c1 32521
#define spriteshipCGBPal4c2 1087
#define spriteshipCGBPal4c3 0

/* Gameboy Color palette 5 */
#define spriteshipCGBPal5c0 16417
#define spriteshipCGBPal5c1 1087
#define spriteshipCGBPal5c2 82
#define spriteshipCGBPal5c3 0

/* Gameboy Color palette 6 */
#define spriteshipCGBPal6c0 16417
#define spriteshipCGBPal6c1 9193
#define spriteshipCGBPal6c2 1568
#define spriteshipCGBPal6c3 0

/* Gameboy Color palette 7 */
#define spriteshipCGBPal7c0 16417
#define spriteshipCGBPal7c1 32767
#define spriteshipCGBPal7c2 13741
#define spriteshipCGBPal7c3 0
/* CGBpalette entries. */
extern unsigned char spriteshipCGB[];
/* Start of tile array. */
extern unsigned char spriteship[];

/* End of SRC/SPRITESHIP.H */
