/*

 SRC/SPRITE_ROCKET.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 32 x 32
  Tiles                : 0 to 0

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define spriterocketBank 0

/* Super Gameboy palette 0 */
#define spriterocketSGBPal0c0 6076
#define spriterocketSGBPal0c1 8935
#define spriterocketSGBPal0c2 6596
#define spriterocketSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define spriterocketSGBPal1c0 6076
#define spriterocketSGBPal1c1 8935
#define spriterocketSGBPal1c2 6596
#define spriterocketSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define spriterocketSGBPal2c0 6076
#define spriterocketSGBPal2c1 8935
#define spriterocketSGBPal2c2 6596
#define spriterocketSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define spriterocketSGBPal3c0 6076
#define spriterocketSGBPal3c1 8935
#define spriterocketSGBPal3c2 6596
#define spriterocketSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define spriterocketCGBPal0c0 32767
#define spriterocketCGBPal0c1 32767
#define spriterocketCGBPal0c2 23254
#define spriterocketCGBPal0c3 0

/* Gameboy Color palette 1 */
#define spriterocketCGBPal1c0 16417
#define spriterocketCGBPal1c1 1087
#define spriterocketCGBPal1c2 82
#define spriterocketCGBPal1c3 0

/* Gameboy Color palette 2 */
#define spriterocketCGBPal2c0 16417
#define spriterocketCGBPal2c1 9193
#define spriterocketCGBPal2c2 1568
#define spriterocketCGBPal2c3 0

/* Gameboy Color palette 3 */
#define spriterocketCGBPal3c0 16417
#define spriterocketCGBPal3c1 9213
#define spriterocketCGBPal3c2 724
#define spriterocketCGBPal3c3 0

/* Gameboy Color palette 4 */
#define spriterocketCGBPal4c0 16417
#define spriterocketCGBPal4c1 32521
#define spriterocketCGBPal4c2 6142
#define spriterocketCGBPal4c3 0

/* Gameboy Color palette 5 */
#define spriterocketCGBPal5c0 16417
#define spriterocketCGBPal5c1 32521
#define spriterocketCGBPal5c2 1087
#define spriterocketCGBPal5c3 0

/* Gameboy Color palette 6 */
#define spriterocketCGBPal6c0 16417
#define spriterocketCGBPal6c1 32521
#define spriterocketCGBPal6c2 31839
#define spriterocketCGBPal6c3 0

/* Gameboy Color palette 7 */
#define spriterocketCGBPal7c0 17441
#define spriterocketCGBPal7c1 32767
#define spriterocketCGBPal7c2 223
#define spriterocketCGBPal7c3 0
/* CGBpalette entries. */
extern unsigned char spriterocketCGB[];
/* Start of tile array. */
extern unsigned char spriterocket[];

/* End of SRC/SPRITE_ROCKET.H */
