/*

 TILES_MENU.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 255

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define tiles_menuBank 0

/* Super Gameboy palette 0 */
#define tiles_menuSGBPal0c0 6076
#define tiles_menuSGBPal0c1 8935
#define tiles_menuSGBPal0c2 6596
#define tiles_menuSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define tiles_menuSGBPal1c0 6076
#define tiles_menuSGBPal1c1 8935
#define tiles_menuSGBPal1c2 6596
#define tiles_menuSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define tiles_menuSGBPal2c0 6076
#define tiles_menuSGBPal2c1 8935
#define tiles_menuSGBPal2c2 6596
#define tiles_menuSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define tiles_menuSGBPal3c0 6076
#define tiles_menuSGBPal3c1 8935
#define tiles_menuSGBPal3c2 6596
#define tiles_menuSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define tiles_menuCGBPal0c0 32767
#define tiles_menuCGBPal0c1 20083
#define tiles_menuCGBPal0c2 10570
#define tiles_menuCGBPal0c3 0

/* Gameboy Color palette 1 */
#define tiles_menuCGBPal1c0 32767
#define tiles_menuCGBPal1c1 8479
#define tiles_menuCGBPal1c2 17
#define tiles_menuCGBPal1c3 0

/* Gameboy Color palette 2 */
#define tiles_menuCGBPal2c0 19458
#define tiles_menuCGBPal2c1 32767
#define tiles_menuCGBPal2c2 13741
#define tiles_menuCGBPal2c3 0

/* Gameboy Color palette 3 */
#define tiles_menuCGBPal3c0 19458
#define tiles_menuCGBPal3c1 14317
#define tiles_menuCGBPal3c2 3616
#define tiles_menuCGBPal3c3 0

/* Gameboy Color palette 4 */
#define tiles_menuCGBPal4c0 19458
#define tiles_menuCGBPal4c1 31411
#define tiles_menuCGBPal4c2 32102
#define tiles_menuCGBPal4c3 0

/* Gameboy Color palette 5 */
#define tiles_menuCGBPal5c0 19458
#define tiles_menuCGBPal5c1 29214
#define tiles_menuCGBPal5c2 3616
#define tiles_menuCGBPal5c3 0

/* Gameboy Color palette 6 */
#define tiles_menuCGBPal6c0 19458
#define tiles_menuCGBPal6c1 23254
#define tiles_menuCGBPal6c2 31
#define tiles_menuCGBPal6c3 0

/* Gameboy Color palette 7 */
#define tiles_menuCGBPal7c0 19458
#define tiles_menuCGBPal7c1 9887
#define tiles_menuCGBPal7c2 375
#define tiles_menuCGBPal7c3 0
/* CGBpalette entries. */
extern unsigned char tiles_menuCGB[];
/* Start of tile array. */
extern unsigned char tiles_menu[];

/* End of TILES_MENU.H */
