/*

 TILES_LOADING.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 255

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define tiles_loadingBank 0

/* Super Gameboy palette 0 */
#define tiles_loadingSGBPal0c0 6076
#define tiles_loadingSGBPal0c1 8935
#define tiles_loadingSGBPal0c2 6596
#define tiles_loadingSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define tiles_loadingSGBPal1c0 6076
#define tiles_loadingSGBPal1c1 8935
#define tiles_loadingSGBPal1c2 6596
#define tiles_loadingSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define tiles_loadingSGBPal2c0 6076
#define tiles_loadingSGBPal2c1 8935
#define tiles_loadingSGBPal2c2 6596
#define tiles_loadingSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define tiles_loadingSGBPal3c0 6076
#define tiles_loadingSGBPal3c1 8935
#define tiles_loadingSGBPal3c2 6596
#define tiles_loadingSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define tiles_loadingCGBPal0c0 32767
#define tiles_loadingCGBPal0c1 31578
#define tiles_loadingCGBPal0c2 32237
#define tiles_loadingCGBPal0c3 3072

/* Gameboy Color palette 1 */
#define tiles_loadingCGBPal1c0 32767
#define tiles_loadingCGBPal1c1 31
#define tiles_loadingCGBPal1c2 2497
#define tiles_loadingCGBPal1c3 0

/* Gameboy Color palette 2 */
#define tiles_loadingCGBPal2c0 957
#define tiles_loadingCGBPal2c1 21460
#define tiles_loadingCGBPal2c2 2497
#define tiles_loadingCGBPal2c3 0

/* Gameboy Color palette 3 */
#define tiles_loadingCGBPal3c0 32767
#define tiles_loadingCGBPal3c1 21460
#define tiles_loadingCGBPal3c2 2497
#define tiles_loadingCGBPal3c3 0

/* Gameboy Color palette 4 */
#define tiles_loadingCGBPal4c0 32767
#define tiles_loadingCGBPal4c1 21140
#define tiles_loadingCGBPal4c2 10570
#define tiles_loadingCGBPal4c3 0

/* Gameboy Color palette 5 */
#define tiles_loadingCGBPal5c0 32767
#define tiles_loadingCGBPal5c1 21140
#define tiles_loadingCGBPal5c2 31829
#define tiles_loadingCGBPal5c3 0

/* Gameboy Color palette 6 */
#define tiles_loadingCGBPal6c0 32767
#define tiles_loadingCGBPal6c1 28222
#define tiles_loadingCGBPal6c2 31829
#define tiles_loadingCGBPal6c3 0

/* Gameboy Color palette 7 */
#define tiles_loadingCGBPal7c0 31508
#define tiles_loadingCGBPal7c1 28222
#define tiles_loadingCGBPal7c2 31829
#define tiles_loadingCGBPal7c3 0
/* CGBpalette entries. */
extern unsigned char tiles_loadingCGB[];
/* Start of tile array. */
extern unsigned char tiles_loading[];

/* End of TILES_LOADING.H */
