/*

 TILES.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 16 x 16
  Tiles                : 0 to 0

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define MapTileBank 0

/* Super Gameboy palette 0 */
#define MapTileSGBPal0c0 6076
#define MapTileSGBPal0c1 8935
#define MapTileSGBPal0c2 6596
#define MapTileSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define MapTileSGBPal1c0 6076
#define MapTileSGBPal1c1 8935
#define MapTileSGBPal1c2 6596
#define MapTileSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define MapTileSGBPal2c0 6076
#define MapTileSGBPal2c1 8935
#define MapTileSGBPal2c2 6596
#define MapTileSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define MapTileSGBPal3c0 6076
#define MapTileSGBPal3c1 8935
#define MapTileSGBPal3c2 6596
#define MapTileSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define MapTileCGBPal0c0 16417
#define MapTileCGBPal0c1 32521
#define MapTileCGBPal0c2 31839
#define MapTileCGBPal0c3 0

/* Gameboy Color palette 1 */
#define MapTileCGBPal1c0 16417
#define MapTileCGBPal1c1 32063
#define MapTileCGBPal1c2 20502
#define MapTileCGBPal1c3 0

/* Gameboy Color palette 2 */
#define MapTileCGBPal2c0 16417
#define MapTileCGBPal2c1 32521
#define MapTileCGBPal2c2 6142
#define MapTileCGBPal2c3 0

/* Gameboy Color palette 3 */
#define MapTileCGBPal3c0 16417
#define MapTileCGBPal3c1 9213
#define MapTileCGBPal3c2 724
#define MapTileCGBPal3c3 0

/* Gameboy Color palette 4 */
#define MapTileCGBPal4c0 16417
#define MapTileCGBPal4c1 32521
#define MapTileCGBPal4c2 1087
#define MapTileCGBPal4c3 0

/* Gameboy Color palette 5 */
#define MapTileCGBPal5c0 16417
#define MapTileCGBPal5c1 1087
#define MapTileCGBPal5c2 82
#define MapTileCGBPal5c3 0

/* Gameboy Color palette 6 */
#define MapTileCGBPal6c0 16417
#define MapTileCGBPal6c1 9193
#define MapTileCGBPal6c2 1568
#define MapTileCGBPal6c3 0

/* Gameboy Color palette 7 */
#define MapTileCGBPal7c0 16417
#define MapTileCGBPal7c1 32767
#define MapTileCGBPal7c2 13741
#define MapTileCGBPal7c3 0
/* CGBpalette entries. */
extern unsigned char MapTileCGB[];
/* Start of tile array. */
extern unsigned char MapTile[];

/* End of TILES.H */
