/*

 TILES_LEVEL1.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 210

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define tiles_level1Bank 0

/* Super Gameboy palette 0 */
#define tiles_level1SGBPal0c0 6076
#define tiles_level1SGBPal0c1 8935
#define tiles_level1SGBPal0c2 6596
#define tiles_level1SGBPal0c3 5344

/* Super Gameboy palette 1 */
#define tiles_level1SGBPal1c0 6076
#define tiles_level1SGBPal1c1 8935
#define tiles_level1SGBPal1c2 6596
#define tiles_level1SGBPal1c3 5344

/* Super Gameboy palette 2 */
#define tiles_level1SGBPal2c0 6076
#define tiles_level1SGBPal2c1 8935
#define tiles_level1SGBPal2c2 6596
#define tiles_level1SGBPal2c3 5344

/* Super Gameboy palette 3 */
#define tiles_level1SGBPal3c0 6076
#define tiles_level1SGBPal3c1 8935
#define tiles_level1SGBPal3c2 6596
#define tiles_level1SGBPal3c3 5344

/* Gameboy Color palette 0 */
#define tiles_level1CGBPal0c0 32291
#define tiles_level1CGBPal0c1 30174
#define tiles_level1CGBPal0c2 19475
#define tiles_level1CGBPal0c3 0

/* Gameboy Color palette 1 */
#define tiles_level1CGBPal1c0 10111
#define tiles_level1CGBPal1c1 502
#define tiles_level1CGBPal1c2 19475
#define tiles_level1CGBPal1c3 0

/* Gameboy Color palette 2 */
#define tiles_level1CGBPal2c0 32291
#define tiles_level1CGBPal2c1 502
#define tiles_level1CGBPal2c2 19475
#define tiles_level1CGBPal2c3 0

/* Gameboy Color palette 3 */
#define tiles_level1CGBPal3c0 30653
#define tiles_level1CGBPal3c1 21140
#define tiles_level1CGBPal3c2 12684
#define tiles_level1CGBPal3c3 0

/* Gameboy Color palette 4 */
#define tiles_level1CGBPal4c0 32291
#define tiles_level1CGBPal4c1 20435
#define tiles_level1CGBPal4c2 547
#define tiles_level1CGBPal4c3 0

/* Gameboy Color palette 5 */
#define tiles_level1CGBPal5c0 32291
#define tiles_level1CGBPal5c1 9695
#define tiles_level1CGBPal5c2 118
#define tiles_level1CGBPal5c3 0

/* Gameboy Color palette 6 */
#define tiles_level1CGBPal6c0 31612
#define tiles_level1CGBPal6c1 31248
#define tiles_level1CGBPal6c2 31840
#define tiles_level1CGBPal6c3 0

/* Gameboy Color palette 7 */
#define tiles_level1CGBPal7c0 10111
#define tiles_level1CGBPal7c1 502
#define tiles_level1CGBPal7c2 1293
#define tiles_level1CGBPal7c3 0
/* CGBpalette entries. */
extern unsigned char tiles_level1CGB[];
/* Start of tile array. */
extern unsigned char tiles_level1[];

/* End of TILES_LEVEL1.H */
