/*

 MAP_FLOGO.H

 Map Include File.

 Info:
   Section       : Map
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : menu.gbr
   Plane count   : 2 planes (16 bits)
   Plane order   : Planes are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define map_flogoWidth 20
#define map_flogoHeight 18
#define map_flogoBank 0

#define map_flogo map_flogoPLN0
extern unsigned char map_flogoPLN0[];
extern unsigned char map_flogoPLN1[];

/* End of MAP_FLOGO.H */
