/*

 SRC/SPRITEUFO.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 16 x 16
  Tiles                : 0 to 3

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define spriteufoBank 0

/* Super Gameboy palette 0 */
#define spriteufoSGBPal0c0 6076
#define spriteufoSGBPal0c1 8935
#define spriteufoSGBPal0c2 6596
#define spriteufoSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define spriteufoSGBPal1c0 6076
#define spriteufoSGBPal1c1 8935
#define spriteufoSGBPal1c2 6596
#define spriteufoSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define spriteufoSGBPal2c0 6076
#define spriteufoSGBPal2c1 8935
#define spriteufoSGBPal2c2 6596
#define spriteufoSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define spriteufoSGBPal3c0 6076
#define spriteufoSGBPal3c1 8935
#define spriteufoSGBPal3c2 6596
#define spriteufoSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define spriteufoCGBPal0c0 16417
#define spriteufoCGBPal0c1 32521
#define spriteufoCGBPal0c2 31839
#define spriteufoCGBPal0c3 0

/* Gameboy Color palette 1 */
#define spriteufoCGBPal1c0 16417
#define spriteufoCGBPal1c1 32063
#define spriteufoCGBPal1c2 20502
#define spriteufoCGBPal1c3 0

/* Gameboy Color palette 2 */
#define spriteufoCGBPal2c0 16417
#define spriteufoCGBPal2c1 32521
#define spriteufoCGBPal2c2 6142
#define spriteufoCGBPal2c3 0

/* Gameboy Color palette 3 */
#define spriteufoCGBPal3c0 16417
#define spriteufoCGBPal3c1 9213
#define spriteufoCGBPal3c2 724
#define spriteufoCGBPal3c3 0

/* Gameboy Color palette 4 */
#define spriteufoCGBPal4c0 16417
#define spriteufoCGBPal4c1 32521
#define spriteufoCGBPal4c2 1087
#define spriteufoCGBPal4c3 0

/* Gameboy Color palette 5 */
#define spriteufoCGBPal5c0 16417
#define spriteufoCGBPal5c1 1087
#define spriteufoCGBPal5c2 82
#define spriteufoCGBPal5c3 0

/* Gameboy Color palette 6 */
#define spriteufoCGBPal6c0 16417
#define spriteufoCGBPal6c1 9193
#define spriteufoCGBPal6c2 1568
#define spriteufoCGBPal6c3 0

/* Gameboy Color palette 7 */
#define spriteufoCGBPal7c0 16417
#define spriteufoCGBPal7c1 32767
#define spriteufoCGBPal7c2 13741
#define spriteufoCGBPal7c3 0
/* CGBpalette entries. */
extern unsigned char spriteufoCGB[];
/* Start of tile array. */
extern unsigned char spriteufo[];

/* End of SRC/SPRITEUFO.H */
