/*

 SRC/SPRITEARROW.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 16 x 16
  Tiles                : 0 to 2

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define spritearrowBank 0

/* Super Gameboy palette 0 */
#define spritearrowSGBPal0c0 6076
#define spritearrowSGBPal0c1 8935
#define spritearrowSGBPal0c2 6596
#define spritearrowSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define spritearrowSGBPal1c0 6076
#define spritearrowSGBPal1c1 8935
#define spritearrowSGBPal1c2 6596
#define spritearrowSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define spritearrowSGBPal2c0 6076
#define spritearrowSGBPal2c1 8935
#define spritearrowSGBPal2c2 6596
#define spritearrowSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define spritearrowSGBPal3c0 6076
#define spritearrowSGBPal3c1 8935
#define spritearrowSGBPal3c2 6596
#define spritearrowSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define spritearrowCGBPal0c0 16417
#define spritearrowCGBPal0c1 32521
#define spritearrowCGBPal0c2 31839
#define spritearrowCGBPal0c3 0

/* Gameboy Color palette 1 */
#define spritearrowCGBPal1c0 16417
#define spritearrowCGBPal1c1 32063
#define spritearrowCGBPal1c2 20502
#define spritearrowCGBPal1c3 0

/* Gameboy Color palette 2 */
#define spritearrowCGBPal2c0 16417
#define spritearrowCGBPal2c1 32521
#define spritearrowCGBPal2c2 6142
#define spritearrowCGBPal2c3 0

/* Gameboy Color palette 3 */
#define spritearrowCGBPal3c0 16417
#define spritearrowCGBPal3c1 9213
#define spritearrowCGBPal3c2 724
#define spritearrowCGBPal3c3 0

/* Gameboy Color palette 4 */
#define spritearrowCGBPal4c0 16417
#define spritearrowCGBPal4c1 32521
#define spritearrowCGBPal4c2 1087
#define spritearrowCGBPal4c3 0

/* Gameboy Color palette 5 */
#define spritearrowCGBPal5c0 16417
#define spritearrowCGBPal5c1 1087
#define spritearrowCGBPal5c2 82
#define spritearrowCGBPal5c3 0

/* Gameboy Color palette 6 */
#define spritearrowCGBPal6c0 16417
#define spritearrowCGBPal6c1 9193
#define spritearrowCGBPal6c2 1568
#define spritearrowCGBPal6c3 0

/* Gameboy Color palette 7 */
#define spritearrowCGBPal7c0 16417
#define spritearrowCGBPal7c1 32767
#define spritearrowCGBPal7c2 13741
#define spritearrowCGBPal7c3 0
/* CGBpalette entries. */
extern unsigned char spritearrowCGB[];
/* Start of tile array. */
extern unsigned char spritearrow[];

/* End of SRC/SPRITEARROW.H */
