/*

 TILES_LEVEL1.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 255

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define tiles_level1Bank 0

/* Super Gameboy palette 0 */
#define tiles_level1SGBPal0c0 6076
#define tiles_level1SGBPal0c1 8935
#define tiles_level1SGBPal0c2 6596
#define tiles_level1SGBPal0c3 5344

/* Super Gameboy palette 1 */
#define tiles_level1SGBPal1c0 6076
#define tiles_level1SGBPal1c1 8935
#define tiles_level1SGBPal1c2 6596
#define tiles_level1SGBPal1c3 5344

/* Super Gameboy palette 2 */
#define tiles_level1SGBPal2c0 6076
#define tiles_level1SGBPal2c1 8935
#define tiles_level1SGBPal2c2 6596
#define tiles_level1SGBPal2c3 5344

/* Super Gameboy palette 3 */
#define tiles_level1SGBPal3c0 6076
#define tiles_level1SGBPal3c1 8935
#define tiles_level1SGBPal3c2 6596
#define tiles_level1SGBPal3c3 5344

/* Gameboy Color palette 0 */
#define tiles_level1CGBPal0c0 31810
#define tiles_level1CGBPal0c1 31578
#define tiles_level1CGBPal0c2 31184
#define tiles_level1CGBPal0c3 23555

/* Gameboy Color palette 1 */
#define tiles_level1CGBPal1c0 31582
#define tiles_level1CGBPal1c1 28991
#define tiles_level1CGBPal1c2 19474
#define tiles_level1CGBPal1c3 0

/* Gameboy Color palette 2 */
#define tiles_level1CGBPal2c0 21461
#define tiles_level1CGBPal2c1 9194
#define tiles_level1CGBPal2c2 1473
#define tiles_level1CGBPal2c3 5344

/* Gameboy Color palette 3 */
#define tiles_level1CGBPal3c0 26425
#define tiles_level1CGBPal3c1 9194
#define tiles_level1CGBPal3c2 1473
#define tiles_level1CGBPal3c3 10570

/* Gameboy Color palette 4 */
#define tiles_level1CGBPal4c0 32733
#define tiles_level1CGBPal4c1 15166
#define tiles_level1CGBPal4c2 383
#define tiles_level1CGBPal4c3 0

/* Gameboy Color palette 5 */
#define tiles_level1CGBPal5c0 6076
#define tiles_level1CGBPal5c1 8935
#define tiles_level1CGBPal5c2 6596
#define tiles_level1CGBPal5c3 5344

/* Gameboy Color palette 6 */
#define tiles_level1CGBPal6c0 6076
#define tiles_level1CGBPal6c1 8935
#define tiles_level1CGBPal6c2 6596
#define tiles_level1CGBPal6c3 5344

/* Gameboy Color palette 7 */
#define tiles_level1CGBPal7c0 6076
#define tiles_level1CGBPal7c1 8935
#define tiles_level1CGBPal7c2 6596
#define tiles_level1CGBPal7c3 5344
/* CGBpalette entries. */
extern unsigned char tiles_level1CGB[];
/* Start of tile array. */
extern unsigned char tiles_level1[];

/* End of TILES_LEVEL1.H */
