/*

 WIN_LEVEL1.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 3
   Tile set      : level1.gbr
   Plane count   : 2 planes (16 bits)
   Plane order   : Planes are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define win_level1Width 20
#define win_level1Height 3
#define win_level1Bank 0

#define win_level1 win_level1PLN0
extern unsigned char win_level1PLN0[];
extern unsigned char win_level1PLN1[];

/* End of WIN_LEVEL1.H */
