#ifndef ZGBMAIN_H
#define ZGBMAIN_H

#define STATES \
_STATE(STATE_MENU)\
_STATE(STATE_GAME)\
_STATE(STATE_CREDITS)\
_STATE(STATE_LEVEL1)\
STATE_DEF_END

#define SPRITES \
_SPRITE_DMG(SPRITE_PLAYER, player, 3, FRAME_16x16, 3)\
_SPRITE_DMG(SPRITE_POINTER, pointer, 3, FRAME_16x16, 4)\
_SPRITE_DMG(SPRITE_SHIP, spriteship, 3, FRAME_16x16, 4)\
_SPRITE_DMG(SPRITE_UFO, spriteufo, 3, FRAME_16x16, 4)\
_SPRITE_DMG(SPRITE_ARROW, spritearrow, 3, FRAME_16x16, 3)\
_SPRITE_DMG(SPRITE_ROCKET, spriterocket, 3, FRAME_32x32, 1)\
SPRITE_DEF_END

#include "ZGBMain_Init.h"

#endif