/*

 SRC/DOL.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 16 x 16
  Tiles                : 0 to 1

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define dolBank 0

/* Super Gameboy palette 0 */
#define dolSGBPal0c0 6076
#define dolSGBPal0c1 8935
#define dolSGBPal0c2 6596
#define dolSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define dolSGBPal1c0 6076
#define dolSGBPal1c1 8935
#define dolSGBPal1c2 6596
#define dolSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define dolSGBPal2c0 6076
#define dolSGBPal2c1 8935
#define dolSGBPal2c2 6596
#define dolSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define dolSGBPal3c0 6076
#define dolSGBPal3c1 8935
#define dolSGBPal3c2 6596
#define dolSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define dolCGBPal0c0 31741
#define dolCGBPal0c1 32765
#define dolCGBPal0c2 19026
#define dolCGBPal0c3 0

/* Gameboy Color palette 1 */
#define dolCGBPal1c0 6076
#define dolCGBPal1c1 8935
#define dolCGBPal1c2 6596
#define dolCGBPal1c3 5344

/* Gameboy Color palette 2 */
#define dolCGBPal2c0 6076
#define dolCGBPal2c1 8935
#define dolCGBPal2c2 6596
#define dolCGBPal2c3 5344

/* Gameboy Color palette 3 */
#define dolCGBPal3c0 6076
#define dolCGBPal3c1 8935
#define dolCGBPal3c2 6596
#define dolCGBPal3c3 5344

/* Gameboy Color palette 4 */
#define dolCGBPal4c0 6076
#define dolCGBPal4c1 8935
#define dolCGBPal4c2 6596
#define dolCGBPal4c3 5344

/* Gameboy Color palette 5 */
#define dolCGBPal5c0 6076
#define dolCGBPal5c1 8935
#define dolCGBPal5c2 6596
#define dolCGBPal5c3 5344

/* Gameboy Color palette 6 */
#define dolCGBPal6c0 6076
#define dolCGBPal6c1 8935
#define dolCGBPal6c2 6596
#define dolCGBPal6c3 5344

/* Gameboy Color palette 7 */
#define dolCGBPal7c0 6076
#define dolCGBPal7c1 8935
#define dolCGBPal7c2 6596
#define dolCGBPal7c3 5344
/* CGBpalette entries. */
extern unsigned char dolCGB[];
/* Start of tile array. */
extern unsigned char dol[];

/* End of SRC/DOL.H */
