/*

 SRC/ENEMY3.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 16 x 16
  Tiles                : 0 to 3

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define enemy3Bank 0

/* Super Gameboy palette 0 */
#define enemy3SGBPal0c0 6076
#define enemy3SGBPal0c1 8935
#define enemy3SGBPal0c2 6596
#define enemy3SGBPal0c3 5344

/* Super Gameboy palette 1 */
#define enemy3SGBPal1c0 6076
#define enemy3SGBPal1c1 8935
#define enemy3SGBPal1c2 6596
#define enemy3SGBPal1c3 5344

/* Super Gameboy palette 2 */
#define enemy3SGBPal2c0 6076
#define enemy3SGBPal2c1 8935
#define enemy3SGBPal2c2 6596
#define enemy3SGBPal2c3 5344

/* Super Gameboy palette 3 */
#define enemy3SGBPal3c0 6076
#define enemy3SGBPal3c1 8935
#define enemy3SGBPal3c2 6596
#define enemy3SGBPal3c3 5344

/* Gameboy Color palette 0 */
#define enemy3CGBPal0c0 31741
#define enemy3CGBPal0c1 32765
#define enemy3CGBPal0c2 19026
#define enemy3CGBPal0c3 0

/* Gameboy Color palette 1 */
#define enemy3CGBPal1c0 6076
#define enemy3CGBPal1c1 8935
#define enemy3CGBPal1c2 6596
#define enemy3CGBPal1c3 5344

/* Gameboy Color palette 2 */
#define enemy3CGBPal2c0 6076
#define enemy3CGBPal2c1 8935
#define enemy3CGBPal2c2 6596
#define enemy3CGBPal2c3 5344

/* Gameboy Color palette 3 */
#define enemy3CGBPal3c0 6076
#define enemy3CGBPal3c1 8935
#define enemy3CGBPal3c2 6596
#define enemy3CGBPal3c3 5344

/* Gameboy Color palette 4 */
#define enemy3CGBPal4c0 6076
#define enemy3CGBPal4c1 8935
#define enemy3CGBPal4c2 6596
#define enemy3CGBPal4c3 5344

/* Gameboy Color palette 5 */
#define enemy3CGBPal5c0 6076
#define enemy3CGBPal5c1 8935
#define enemy3CGBPal5c2 6596
#define enemy3CGBPal5c3 5344

/* Gameboy Color palette 6 */
#define enemy3CGBPal6c0 6076
#define enemy3CGBPal6c1 8935
#define enemy3CGBPal6c2 6596
#define enemy3CGBPal6c3 5344

/* Gameboy Color palette 7 */
#define enemy3CGBPal7c0 6076
#define enemy3CGBPal7c1 8935
#define enemy3CGBPal7c2 6596
#define enemy3CGBPal7c3 5344
/* CGBpalette entries. */
extern unsigned char enemy3CGB[];
/* Start of tile array. */
extern unsigned char enemy3[];

/* End of SRC/ENEMY3.H */
