/*

 SRC/HUMAN.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 16 x 16
  Tiles                : 0 to 13

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define HumanBank 0

/* Super Gameboy palette 0 */
#define HumanSGBPal0c0 6076
#define HumanSGBPal0c1 8935
#define HumanSGBPal0c2 6596
#define HumanSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define HumanSGBPal1c0 6076
#define HumanSGBPal1c1 8935
#define HumanSGBPal1c2 6596
#define HumanSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define HumanSGBPal2c0 6076
#define HumanSGBPal2c1 8935
#define HumanSGBPal2c2 6596
#define HumanSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define HumanSGBPal3c0 6076
#define HumanSGBPal3c1 8935
#define HumanSGBPal3c2 6596
#define HumanSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define HumanCGBPal0c0 32557
#define HumanCGBPal0c1 32767
#define HumanCGBPal0c2 5791
#define HumanCGBPal0c3 0

/* Gameboy Color palette 1 */
#define HumanCGBPal1c0 32767
#define HumanCGBPal1c1 22197
#define HumanCGBPal1c2 11627
#define HumanCGBPal1c3 0

/* Gameboy Color palette 2 */
#define HumanCGBPal2c0 32557
#define HumanCGBPal2c1 32767
#define HumanCGBPal2c2 223
#define HumanCGBPal2c3 0

/* Gameboy Color palette 3 */
#define HumanCGBPal3c0 32557
#define HumanCGBPal3c1 403
#define HumanCGBPal3c2 23872
#define HumanCGBPal3c3 0

/* Gameboy Color palette 4 */
#define HumanCGBPal4c0 32557
#define HumanCGBPal4c1 403
#define HumanCGBPal4c2 253
#define HumanCGBPal4c3 0

/* Gameboy Color palette 5 */
#define HumanCGBPal5c0 6076
#define HumanCGBPal5c1 8935
#define HumanCGBPal5c2 6596
#define HumanCGBPal5c3 5344

/* Gameboy Color palette 6 */
#define HumanCGBPal6c0 6076
#define HumanCGBPal6c1 8935
#define HumanCGBPal6c2 6596
#define HumanCGBPal6c3 5344

/* Gameboy Color palette 7 */
#define HumanCGBPal7c0 6076
#define HumanCGBPal7c1 8935
#define HumanCGBPal7c2 6596
#define HumanCGBPal7c3 5344
/* CGBpalette entries. */
extern unsigned char HumanCGB[];
/* Start of tile array. */
extern unsigned char Human[];

/* End of SRC/HUMAN.H */
