/*

 MAP_LEVEL2.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 211 x 36
   Tile set      : level2.gbr
   Plane count   : 2 planes (16 bits)
   Plane order   : Planes are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define map_level2Width 211
#define map_level2Height 36
#define map_level2Bank 0

#define map_level2 map_level2PLN0
extern unsigned char map_level2PLN0[];
extern unsigned char map_level2PLN1[];

/* End of MAP_LEVEL2.H */
