/*

 MAP_LEVEL4.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 48 x 144
   Tile set      : level1.gbr
   Plane count   : 2 planes (16 bits)
   Plane order   : Planes are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define map_level4Width 48
#define map_level4Height 144
#define map_level4Bank 0

#define map_level4 map_level4PLN0
extern unsigned char map_level4PLN0[];
extern unsigned char map_level4PLN1[];

/* End of MAP_LEVEL4.H */
