/*

 MAP_LEVEL11.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 211 x 36
   Tile set      : level11.gbr
   Plane count   : 2 planes (16 bits)
   Plane order   : Planes are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define map_level11Width 211
#define map_level11Height 36
#define map_level11Bank 0

#define map_level11 map_level11PLN0
extern unsigned char map_level11PLN0[];
extern unsigned char map_level11PLN1[];

/* End of MAP_LEVEL11.H */
