/*

 MAP_VILLAGE.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 90 x 36
   Tile set      : Village.gbr
   Plane count   : 2 planes (16 bits)
   Plane order   : Planes are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define map_villageWidth 90
#define map_villageHeight 36
#define map_villageBank 0

#define map_village map_villagePLN0
extern unsigned char map_villagePLN0[];
extern unsigned char map_villagePLN1[];

/* End of MAP_VILLAGE.H */
