/*

 MAP_MAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 32 x 32
   Tile set      : Map_Map.gbr
   Plane count   : 2 planes (16 bits)
   Plane order   : Planes are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define map_mapWidth 32
#define map_mapHeight 32
#define map_mapBank 0

#define map_map map_mapPLN0
extern unsigned char map_mapPLN0[];
extern unsigned char map_mapPLN1[];

/* End of MAP_MAP.H */
