/*

 MAP_MENU.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : menu.gbr
   Plane count   : 2 planes (16 bits)
   Plane order   : Planes are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define map_menuWidth 20
#define map_menuHeight 18
#define map_menuBank 0

#define map_menu map_menuPLN0
extern unsigned char map_menuPLN0[];
extern unsigned char map_menuPLN1[];

/* End of MAP_MENU.H */
