/*

 SRC/MAP_PLAYER.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 16 x 16
  Tiles                : 0 to 1

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define map_playerBank 0

/* Super Gameboy palette 0 */
#define map_playerSGBPal0c0 6076
#define map_playerSGBPal0c1 8935
#define map_playerSGBPal0c2 6596
#define map_playerSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define map_playerSGBPal1c0 6076
#define map_playerSGBPal1c1 8935
#define map_playerSGBPal1c2 6596
#define map_playerSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define map_playerSGBPal2c0 6076
#define map_playerSGBPal2c1 8935
#define map_playerSGBPal2c2 6596
#define map_playerSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define map_playerSGBPal3c0 6076
#define map_playerSGBPal3c1 8935
#define map_playerSGBPal3c2 6596
#define map_playerSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define map_playerCGBPal0c0 32557
#define map_playerCGBPal0c1 32767
#define map_playerCGBPal0c2 5791
#define map_playerCGBPal0c3 0

/* Gameboy Color palette 1 */
#define map_playerCGBPal1c0 32767
#define map_playerCGBPal1c1 22197
#define map_playerCGBPal1c2 11627
#define map_playerCGBPal1c3 0

/* Gameboy Color palette 2 */
#define map_playerCGBPal2c0 32557
#define map_playerCGBPal2c1 32767
#define map_playerCGBPal2c2 223
#define map_playerCGBPal2c3 0

/* Gameboy Color palette 3 */
#define map_playerCGBPal3c0 32557
#define map_playerCGBPal3c1 403
#define map_playerCGBPal3c2 23872
#define map_playerCGBPal3c3 0

/* Gameboy Color palette 4 */
#define map_playerCGBPal4c0 32557
#define map_playerCGBPal4c1 403
#define map_playerCGBPal4c2 253
#define map_playerCGBPal4c3 0

/* Gameboy Color palette 5 */
#define map_playerCGBPal5c0 32557
#define map_playerCGBPal5c1 801
#define map_playerCGBPal5c2 12684
#define map_playerCGBPal5c3 0

/* Gameboy Color palette 6 */
#define map_playerCGBPal6c0 32557
#define map_playerCGBPal6c1 7039
#define map_playerCGBPal6c2 307
#define map_playerCGBPal6c3 0

/* Gameboy Color palette 7 */
#define map_playerCGBPal7c0 6076
#define map_playerCGBPal7c1 8935
#define map_playerCGBPal7c2 6596
#define map_playerCGBPal7c3 5344
/* CGBpalette entries. */
extern unsigned char map_playerCGB[];
/* Start of tile array. */
extern unsigned char map_player[];

/* End of SRC/MAP_PLAYER.H */
