/*

 MAP_CREDITS.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : Credits.gbr
   Plane count   : 2 planes (16 bits)
   Plane order   : Planes are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define map_creditsWidth 20
#define map_creditsHeight 18
#define map_creditsBank 0

#define map_credits map_creditsPLN0
extern unsigned char map_creditsPLN0[];
extern unsigned char map_creditsPLN1[];

/* End of MAP_CREDITS.H */
