/*

 SRC/POLLENB.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 32 x 32
  Tiles                : 0 to 1

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define pollenbBank 0

/* Super Gameboy palette 0 */
#define pollenbSGBPal0c0 6076
#define pollenbSGBPal0c1 8935
#define pollenbSGBPal0c2 6596
#define pollenbSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define pollenbSGBPal1c0 6076
#define pollenbSGBPal1c1 8935
#define pollenbSGBPal1c2 6596
#define pollenbSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define pollenbSGBPal2c0 6076
#define pollenbSGBPal2c1 8935
#define pollenbSGBPal2c2 6596
#define pollenbSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define pollenbSGBPal3c0 6076
#define pollenbSGBPal3c1 8935
#define pollenbSGBPal3c2 6596
#define pollenbSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define pollenbCGBPal0c0 32557
#define pollenbCGBPal0c1 32767
#define pollenbCGBPal0c2 5791
#define pollenbCGBPal0c3 0

/* Gameboy Color palette 1 */
#define pollenbCGBPal1c0 32767
#define pollenbCGBPal1c1 22197
#define pollenbCGBPal1c2 11627
#define pollenbCGBPal1c3 0

/* Gameboy Color palette 2 */
#define pollenbCGBPal2c0 32557
#define pollenbCGBPal2c1 32767
#define pollenbCGBPal2c2 223
#define pollenbCGBPal2c3 0

/* Gameboy Color palette 3 */
#define pollenbCGBPal3c0 32557
#define pollenbCGBPal3c1 403
#define pollenbCGBPal3c2 23872
#define pollenbCGBPal3c3 0

/* Gameboy Color palette 4 */
#define pollenbCGBPal4c0 32557
#define pollenbCGBPal4c1 403
#define pollenbCGBPal4c2 253
#define pollenbCGBPal4c3 0

/* Gameboy Color palette 5 */
#define pollenbCGBPal5c0 32557
#define pollenbCGBPal5c1 801
#define pollenbCGBPal5c2 12684
#define pollenbCGBPal5c3 0

/* Gameboy Color palette 6 */
#define pollenbCGBPal6c0 32557
#define pollenbCGBPal6c1 7039
#define pollenbCGBPal6c2 307
#define pollenbCGBPal6c3 0

/* Gameboy Color palette 7 */
#define pollenbCGBPal7c0 6076
#define pollenbCGBPal7c1 8935
#define pollenbCGBPal7c2 6596
#define pollenbCGBPal7c3 5344
/* CGBpalette entries. */
extern unsigned char pollenbCGB[];
/* Start of tile array. */
extern unsigned char pollenb[];

/* End of SRC/POLLENB.H */
