/*

 SRC/POLLENS.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 16 x 16
  Tiles                : 0 to 1

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define pollensBank 0

/* Super Gameboy palette 0 */
#define pollensSGBPal0c0 6076
#define pollensSGBPal0c1 8935
#define pollensSGBPal0c2 6596
#define pollensSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define pollensSGBPal1c0 6076
#define pollensSGBPal1c1 8935
#define pollensSGBPal1c2 6596
#define pollensSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define pollensSGBPal2c0 6076
#define pollensSGBPal2c1 8935
#define pollensSGBPal2c2 6596
#define pollensSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define pollensSGBPal3c0 6076
#define pollensSGBPal3c1 8935
#define pollensSGBPal3c2 6596
#define pollensSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define pollensCGBPal0c0 32557
#define pollensCGBPal0c1 32767
#define pollensCGBPal0c2 5791
#define pollensCGBPal0c3 0

/* Gameboy Color palette 1 */
#define pollensCGBPal1c0 32767
#define pollensCGBPal1c1 22197
#define pollensCGBPal1c2 11627
#define pollensCGBPal1c3 0

/* Gameboy Color palette 2 */
#define pollensCGBPal2c0 32557
#define pollensCGBPal2c1 32767
#define pollensCGBPal2c2 223
#define pollensCGBPal2c3 0

/* Gameboy Color palette 3 */
#define pollensCGBPal3c0 32557
#define pollensCGBPal3c1 403
#define pollensCGBPal3c2 23872
#define pollensCGBPal3c3 0

/* Gameboy Color palette 4 */
#define pollensCGBPal4c0 32557
#define pollensCGBPal4c1 403
#define pollensCGBPal4c2 253
#define pollensCGBPal4c3 0

/* Gameboy Color palette 5 */
#define pollensCGBPal5c0 32557
#define pollensCGBPal5c1 801
#define pollensCGBPal5c2 12684
#define pollensCGBPal5c3 0

/* Gameboy Color palette 6 */
#define pollensCGBPal6c0 32557
#define pollensCGBPal6c1 7039
#define pollensCGBPal6c2 307
#define pollensCGBPal6c3 0

/* Gameboy Color palette 7 */
#define pollensCGBPal7c0 6076
#define pollensCGBPal7c1 8935
#define pollensCGBPal7c2 6596
#define pollensCGBPal7c3 5344
/* CGBpalette entries. */
extern unsigned char pollensCGB[];
/* Start of tile array. */
extern unsigned char pollens[];

/* End of SRC/POLLENS.H */
