/*

 SRC/ROCKET.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 32 x 32
  Tiles                : 0 to 0

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define rocketBank 0

/* Super Gameboy palette 0 */
#define rocketSGBPal0c0 6076
#define rocketSGBPal0c1 8935
#define rocketSGBPal0c2 6596
#define rocketSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define rocketSGBPal1c0 6076
#define rocketSGBPal1c1 8935
#define rocketSGBPal1c2 6596
#define rocketSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define rocketSGBPal2c0 6076
#define rocketSGBPal2c1 8935
#define rocketSGBPal2c2 6596
#define rocketSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define rocketSGBPal3c0 6076
#define rocketSGBPal3c1 8935
#define rocketSGBPal3c2 6596
#define rocketSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define rocketCGBPal0c0 32557
#define rocketCGBPal0c1 32767
#define rocketCGBPal0c2 5791
#define rocketCGBPal0c3 0

/* Gameboy Color palette 1 */
#define rocketCGBPal1c0 32767
#define rocketCGBPal1c1 22197
#define rocketCGBPal1c2 11627
#define rocketCGBPal1c3 0

/* Gameboy Color palette 2 */
#define rocketCGBPal2c0 32557
#define rocketCGBPal2c1 32767
#define rocketCGBPal2c2 223
#define rocketCGBPal2c3 0

/* Gameboy Color palette 3 */
#define rocketCGBPal3c0 6076
#define rocketCGBPal3c1 8935
#define rocketCGBPal3c2 6596
#define rocketCGBPal3c3 5344

/* Gameboy Color palette 4 */
#define rocketCGBPal4c0 6076
#define rocketCGBPal4c1 8935
#define rocketCGBPal4c2 6596
#define rocketCGBPal4c3 5344

/* Gameboy Color palette 5 */
#define rocketCGBPal5c0 6076
#define rocketCGBPal5c1 8935
#define rocketCGBPal5c2 6596
#define rocketCGBPal5c3 5344

/* Gameboy Color palette 6 */
#define rocketCGBPal6c0 6076
#define rocketCGBPal6c1 8935
#define rocketCGBPal6c2 6596
#define rocketCGBPal6c3 5344

/* Gameboy Color palette 7 */
#define rocketCGBPal7c0 6076
#define rocketCGBPal7c1 8935
#define rocketCGBPal7c2 6596
#define rocketCGBPal7c3 5344
/* CGBpalette entries. */
extern unsigned char rocketCGB[];
/* Start of tile array. */
extern unsigned char rocket[];

/* End of SRC/ROCKET.H */
