/*

 TILES_LEVEL11.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 210

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define tiles_level11Bank 0

/* Super Gameboy palette 0 */
#define tiles_level11SGBPal0c0 6076
#define tiles_level11SGBPal0c1 8935
#define tiles_level11SGBPal0c2 6596
#define tiles_level11SGBPal0c3 5344

/* Super Gameboy palette 1 */
#define tiles_level11SGBPal1c0 6076
#define tiles_level11SGBPal1c1 8935
#define tiles_level11SGBPal1c2 6596
#define tiles_level11SGBPal1c3 5344

/* Super Gameboy palette 2 */
#define tiles_level11SGBPal2c0 6076
#define tiles_level11SGBPal2c1 8935
#define tiles_level11SGBPal2c2 6596
#define tiles_level11SGBPal2c3 5344

/* Super Gameboy palette 3 */
#define tiles_level11SGBPal3c0 6076
#define tiles_level11SGBPal3c1 8935
#define tiles_level11SGBPal3c2 6596
#define tiles_level11SGBPal3c3 5344

/* Gameboy Color palette 0 */
#define tiles_level11CGBPal0c0 1009
#define tiles_level11CGBPal0c1 4896
#define tiles_level11CGBPal0c2 2305
#define tiles_level11CGBPal0c3 0

/* Gameboy Color palette 1 */
#define tiles_level11CGBPal1c0 10111
#define tiles_level11CGBPal1c1 337
#define tiles_level11CGBPal1c2 2305
#define tiles_level11CGBPal1c3 0

/* Gameboy Color palette 2 */
#define tiles_level11CGBPal2c0 1009
#define tiles_level11CGBPal2c1 1387
#define tiles_level11CGBPal2c2 2305
#define tiles_level11CGBPal2c3 0

/* Gameboy Color palette 3 */
#define tiles_level11CGBPal3c0 1009
#define tiles_level11CGBPal3c1 1387
#define tiles_level11CGBPal3c2 1155
#define tiles_level11CGBPal3c3 0

/* Gameboy Color palette 4 */
#define tiles_level11CGBPal4c0 14313
#define tiles_level11CGBPal4c1 1387
#define tiles_level11CGBPal4c2 2305
#define tiles_level11CGBPal4c3 0

/* Gameboy Color palette 5 */
#define tiles_level11CGBPal5c0 1009
#define tiles_level11CGBPal5c1 18384
#define tiles_level11CGBPal5c2 2305
#define tiles_level11CGBPal5c3 0

/* Gameboy Color palette 6 */
#define tiles_level11CGBPal6c0 32035
#define tiles_level11CGBPal6c1 32127
#define tiles_level11CGBPal6c2 14355
#define tiles_level11CGBPal6c3 0

/* Gameboy Color palette 7 */
#define tiles_level11CGBPal7c0 10111
#define tiles_level11CGBPal7c1 337
#define tiles_level11CGBPal7c2 1128
#define tiles_level11CGBPal7c3 0
/* CGBpalette entries. */
extern unsigned char tiles_level11CGB[];
/* Start of tile array. */
extern unsigned char tiles_level11[];

/* End of TILES_LEVEL11.H */
