/*

 TILES_MAP.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 42

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define tiles_mapBank 0

/* Super Gameboy palette 0 */
#define tiles_mapSGBPal0c0 6076
#define tiles_mapSGBPal0c1 8935
#define tiles_mapSGBPal0c2 6596
#define tiles_mapSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define tiles_mapSGBPal1c0 6076
#define tiles_mapSGBPal1c1 8935
#define tiles_mapSGBPal1c2 6596
#define tiles_mapSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define tiles_mapSGBPal2c0 6076
#define tiles_mapSGBPal2c1 8935
#define tiles_mapSGBPal2c2 6596
#define tiles_mapSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define tiles_mapSGBPal3c0 6076
#define tiles_mapSGBPal3c1 8935
#define tiles_mapSGBPal3c2 6596
#define tiles_mapSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define tiles_mapCGBPal0c0 32035
#define tiles_mapCGBPal0c1 12267
#define tiles_mapCGBPal0c2 1473
#define tiles_mapCGBPal0c3 0

/* Gameboy Color palette 1 */
#define tiles_mapCGBPal1c0 32035
#define tiles_mapCGBPal1c1 31707
#define tiles_mapCGBPal1c2 32738
#define tiles_mapCGBPal1c3 0

/* Gameboy Color palette 2 */
#define tiles_mapCGBPal2c0 32035
#define tiles_mapCGBPal2c1 7160
#define tiles_mapCGBPal2c2 1451
#define tiles_mapCGBPal2c3 0

/* Gameboy Color palette 3 */
#define tiles_mapCGBPal3c0 32035
#define tiles_mapCGBPal3c1 32098
#define tiles_mapCGBPal3c2 14370
#define tiles_mapCGBPal3c3 0

/* Gameboy Color palette 4 */
#define tiles_mapCGBPal4c0 831
#define tiles_mapCGBPal4c1 307
#define tiles_mapCGBPal4c2 1125
#define tiles_mapCGBPal4c3 0

/* Gameboy Color palette 5 */
#define tiles_mapCGBPal5c0 1226
#define tiles_mapCGBPal5c1 12267
#define tiles_mapCGBPal5c2 1473
#define tiles_mapCGBPal5c3 0

/* Gameboy Color palette 6 */
#define tiles_mapCGBPal6c0 14370
#define tiles_mapCGBPal6c1 12267
#define tiles_mapCGBPal6c2 1473
#define tiles_mapCGBPal6c3 0

/* Gameboy Color palette 7 */
#define tiles_mapCGBPal7c0 31645
#define tiles_mapCGBPal7c1 19026
#define tiles_mapCGBPal7c2 9513
#define tiles_mapCGBPal7c3 0
/* CGBpalette entries. */
extern unsigned char tiles_mapCGB[];
/* Start of tile array. */
extern unsigned char tiles_map[];

/* End of TILES_MAP.H */
