/*

 TILES_CREDITS.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 210

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define tiles_creditsBank 0

/* Super Gameboy palette 0 */
#define tiles_creditsSGBPal0c0 6076
#define tiles_creditsSGBPal0c1 8935
#define tiles_creditsSGBPal0c2 6596
#define tiles_creditsSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define tiles_creditsSGBPal1c0 6076
#define tiles_creditsSGBPal1c1 8935
#define tiles_creditsSGBPal1c2 6596
#define tiles_creditsSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define tiles_creditsSGBPal2c0 6076
#define tiles_creditsSGBPal2c1 8935
#define tiles_creditsSGBPal2c2 6596
#define tiles_creditsSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define tiles_creditsSGBPal3c0 6076
#define tiles_creditsSGBPal3c1 8935
#define tiles_creditsSGBPal3c2 6596
#define tiles_creditsSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define tiles_creditsCGBPal0c0 11393
#define tiles_creditsCGBPal0c1 948
#define tiles_creditsCGBPal0c2 1282
#define tiles_creditsCGBPal0c3 0

/* Gameboy Color palette 1 */
#define tiles_creditsCGBPal1c0 605
#define tiles_creditsCGBPal1c1 813
#define tiles_creditsCGBPal1c2 1153
#define tiles_creditsCGBPal1c3 0

/* Gameboy Color palette 2 */
#define tiles_creditsCGBPal2c0 32035
#define tiles_creditsCGBPal2c1 337
#define tiles_creditsCGBPal2c2 2305
#define tiles_creditsCGBPal2c3 0

/* Gameboy Color palette 3 */
#define tiles_creditsCGBPal3c0 32035
#define tiles_creditsCGBPal3c1 32767
#define tiles_creditsCGBPal3c2 7399
#define tiles_creditsCGBPal3c3 0

/* Gameboy Color palette 4 */
#define tiles_creditsCGBPal4c0 32733
#define tiles_creditsCGBPal4c1 32617
#define tiles_creditsCGBPal4c2 23008
#define tiles_creditsCGBPal4c3 0

/* Gameboy Color palette 5 */
#define tiles_creditsCGBPal5c0 32035
#define tiles_creditsCGBPal5c1 9695
#define tiles_creditsCGBPal5c2 118
#define tiles_creditsCGBPal5c3 0

/* Gameboy Color palette 6 */
#define tiles_creditsCGBPal6c0 32035
#define tiles_creditsCGBPal6c1 31262
#define tiles_creditsCGBPal6c2 22553
#define tiles_creditsCGBPal6c3 0

/* Gameboy Color palette 7 */
#define tiles_creditsCGBPal7c0 32767
#define tiles_creditsCGBPal7c1 32613
#define tiles_creditsCGBPal7c2 7399
#define tiles_creditsCGBPal7c3 0
/* CGBpalette entries. */
extern unsigned char tiles_creditsCGB[];
/* Start of tile array. */
extern unsigned char tiles_credits[];

/* End of TILES_CREDITS.H */
