/*

 TILES_LEVEL1_W_ANIM.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 8

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define tiles_level1_w_animBank 0

/* Super Gameboy palette 0 */
#define tiles_level1_w_animSGBPal0c0 6076
#define tiles_level1_w_animSGBPal0c1 8935
#define tiles_level1_w_animSGBPal0c2 6596
#define tiles_level1_w_animSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define tiles_level1_w_animSGBPal1c0 6076
#define tiles_level1_w_animSGBPal1c1 8935
#define tiles_level1_w_animSGBPal1c2 6596
#define tiles_level1_w_animSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define tiles_level1_w_animSGBPal2c0 6076
#define tiles_level1_w_animSGBPal2c1 8935
#define tiles_level1_w_animSGBPal2c2 6596
#define tiles_level1_w_animSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define tiles_level1_w_animSGBPal3c0 6076
#define tiles_level1_w_animSGBPal3c1 8935
#define tiles_level1_w_animSGBPal3c2 6596
#define tiles_level1_w_animSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define tiles_level1_w_animCGBPal0c0 32291
#define tiles_level1_w_animCGBPal0c1 30174
#define tiles_level1_w_animCGBPal0c2 19475
#define tiles_level1_w_animCGBPal0c3 0

/* Gameboy Color palette 1 */
#define tiles_level1_w_animCGBPal1c0 10111
#define tiles_level1_w_animCGBPal1c1 502
#define tiles_level1_w_animCGBPal1c2 19475
#define tiles_level1_w_animCGBPal1c3 0

/* Gameboy Color palette 2 */
#define tiles_level1_w_animCGBPal2c0 32291
#define tiles_level1_w_animCGBPal2c1 502
#define tiles_level1_w_animCGBPal2c2 19475
#define tiles_level1_w_animCGBPal2c3 0

/* Gameboy Color palette 3 */
#define tiles_level1_w_animCGBPal3c0 30653
#define tiles_level1_w_animCGBPal3c1 21140
#define tiles_level1_w_animCGBPal3c2 12684
#define tiles_level1_w_animCGBPal3c3 0

/* Gameboy Color palette 4 */
#define tiles_level1_w_animCGBPal4c0 32291
#define tiles_level1_w_animCGBPal4c1 31191
#define tiles_level1_w_animCGBPal4c2 31827
#define tiles_level1_w_animCGBPal4c3 0

/* Gameboy Color palette 5 */
#define tiles_level1_w_animCGBPal5c0 32291
#define tiles_level1_w_animCGBPal5c1 9695
#define tiles_level1_w_animCGBPal5c2 118
#define tiles_level1_w_animCGBPal5c3 0

/* Gameboy Color palette 6 */
#define tiles_level1_w_animCGBPal6c0 31612
#define tiles_level1_w_animCGBPal6c1 31248
#define tiles_level1_w_animCGBPal6c2 31840
#define tiles_level1_w_animCGBPal6c3 0

/* Gameboy Color palette 7 */
#define tiles_level1_w_animCGBPal7c0 32291
#define tiles_level1_w_animCGBPal7c1 31611
#define tiles_level1_w_animCGBPal7c2 7155
#define tiles_level1_w_animCGBPal7c3 700
/* CGBpalette entries. */
extern const unsigned  char tiles_level1_w_animCGB[];
/* Start of tile array. */
extern const unsigned  char tiles_level1_w_anim[];

/* End of TILES_LEVEL1_W_ANIM.H */
