/*

 TILES_VILLAGE.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 156

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define tiles_villageBank 0

/* Super Gameboy palette 0 */
#define tiles_villageSGBPal0c0 6076
#define tiles_villageSGBPal0c1 8935
#define tiles_villageSGBPal0c2 6596
#define tiles_villageSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define tiles_villageSGBPal1c0 6076
#define tiles_villageSGBPal1c1 8935
#define tiles_villageSGBPal1c2 6596
#define tiles_villageSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define tiles_villageSGBPal2c0 6076
#define tiles_villageSGBPal2c1 8935
#define tiles_villageSGBPal2c2 6596
#define tiles_villageSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define tiles_villageSGBPal3c0 6076
#define tiles_villageSGBPal3c1 8935
#define tiles_villageSGBPal3c2 6596
#define tiles_villageSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define tiles_villageCGBPal0c0 32035
#define tiles_villageCGBPal0c1 18384
#define tiles_villageCGBPal0c2 2305
#define tiles_villageCGBPal0c3 0

/* Gameboy Color palette 1 */
#define tiles_villageCGBPal1c0 10111
#define tiles_villageCGBPal1c1 337
#define tiles_villageCGBPal1c2 2305
#define tiles_villageCGBPal1c3 0

/* Gameboy Color palette 2 */
#define tiles_villageCGBPal2c0 32035
#define tiles_villageCGBPal2c1 337
#define tiles_villageCGBPal2c2 2305
#define tiles_villageCGBPal2c3 0

/* Gameboy Color palette 3 */
#define tiles_villageCGBPal3c0 32035
#define tiles_villageCGBPal3c1 32767
#define tiles_villageCGBPal3c2 7399
#define tiles_villageCGBPal3c3 0

/* Gameboy Color palette 4 */
#define tiles_villageCGBPal4c0 32733
#define tiles_villageCGBPal4c1 32617
#define tiles_villageCGBPal4c2 23008
#define tiles_villageCGBPal4c3 0

/* Gameboy Color palette 5 */
#define tiles_villageCGBPal5c0 32035
#define tiles_villageCGBPal5c1 9695
#define tiles_villageCGBPal5c2 118
#define tiles_villageCGBPal5c3 0

/* Gameboy Color palette 6 */
#define tiles_villageCGBPal6c0 32035
#define tiles_villageCGBPal6c1 31262
#define tiles_villageCGBPal6c2 22553
#define tiles_villageCGBPal6c3 0

/* Gameboy Color palette 7 */
#define tiles_villageCGBPal7c0 32767
#define tiles_villageCGBPal7c1 32613
#define tiles_villageCGBPal7c2 7399
#define tiles_villageCGBPal7c3 0
/* CGBpalette entries. */
extern unsigned char tiles_villageCGB[];
/* Start of tile array. */
extern unsigned char tiles_village[];

/* End of TILES_VILLAGE.H */
