/*

 TILES_MAP_W_ANIM.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 8

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define tiles_map_w_animBank 0

/* Super Gameboy palette 0 */
#define tiles_map_w_animSGBPal0c0 6076
#define tiles_map_w_animSGBPal0c1 8935
#define tiles_map_w_animSGBPal0c2 6596
#define tiles_map_w_animSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define tiles_map_w_animSGBPal1c0 6076
#define tiles_map_w_animSGBPal1c1 8935
#define tiles_map_w_animSGBPal1c2 6596
#define tiles_map_w_animSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define tiles_map_w_animSGBPal2c0 6076
#define tiles_map_w_animSGBPal2c1 8935
#define tiles_map_w_animSGBPal2c2 6596
#define tiles_map_w_animSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define tiles_map_w_animSGBPal3c0 6076
#define tiles_map_w_animSGBPal3c1 8935
#define tiles_map_w_animSGBPal3c2 6596
#define tiles_map_w_animSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define tiles_map_w_animCGBPal0c0 32035
#define tiles_map_w_animCGBPal0c1 12267
#define tiles_map_w_animCGBPal0c2 1473
#define tiles_map_w_animCGBPal0c3 0

/* Gameboy Color palette 1 */
#define tiles_map_w_animCGBPal1c0 32035
#define tiles_map_w_animCGBPal1c1 31707
#define tiles_map_w_animCGBPal1c2 32738
#define tiles_map_w_animCGBPal1c3 0

/* Gameboy Color palette 2 */
#define tiles_map_w_animCGBPal2c0 32035
#define tiles_map_w_animCGBPal2c1 7160
#define tiles_map_w_animCGBPal2c2 1451
#define tiles_map_w_animCGBPal2c3 0

/* Gameboy Color palette 3 */
#define tiles_map_w_animCGBPal3c0 32035
#define tiles_map_w_animCGBPal3c1 26427
#define tiles_map_w_animCGBPal3c2 12684
#define tiles_map_w_animCGBPal3c3 0

/* Gameboy Color palette 4 */
#define tiles_map_w_animCGBPal4c0 831
#define tiles_map_w_animCGBPal4c1 307
#define tiles_map_w_animCGBPal4c2 1125
#define tiles_map_w_animCGBPal4c3 0

/* Gameboy Color palette 5 */
#define tiles_map_w_animCGBPal5c0 1226
#define tiles_map_w_animCGBPal5c1 12267
#define tiles_map_w_animCGBPal5c2 1473
#define tiles_map_w_animCGBPal5c3 0

/* Gameboy Color palette 6 */
#define tiles_map_w_animCGBPal6c0 14370
#define tiles_map_w_animCGBPal6c1 12267
#define tiles_map_w_animCGBPal6c2 1473
#define tiles_map_w_animCGBPal6c3 0

/* Gameboy Color palette 7 */
#define tiles_map_w_animCGBPal7c0 31645
#define tiles_map_w_animCGBPal7c1 19026
#define tiles_map_w_animCGBPal7c2 9513
#define tiles_map_w_animCGBPal7c3 0
/* CGBpalette entries. */
extern unsigned char tiles_map_w_animCGB[];
/* Start of tile array. */
extern unsigned char tiles_map_w_anim[];

/* End of TILES_MAP_W_ANIM.H */
