/*

 TILES_LEVEL2.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 210

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define tiles_level2Bank 0

/* Super Gameboy palette 0 */
#define tiles_level2SGBPal0c0 6076
#define tiles_level2SGBPal0c1 8935
#define tiles_level2SGBPal0c2 6596
#define tiles_level2SGBPal0c3 5344

/* Super Gameboy palette 1 */
#define tiles_level2SGBPal1c0 6076
#define tiles_level2SGBPal1c1 8935
#define tiles_level2SGBPal1c2 6596
#define tiles_level2SGBPal1c3 5344

/* Super Gameboy palette 2 */
#define tiles_level2SGBPal2c0 6076
#define tiles_level2SGBPal2c1 8935
#define tiles_level2SGBPal2c2 6596
#define tiles_level2SGBPal2c3 5344

/* Super Gameboy palette 3 */
#define tiles_level2SGBPal3c0 6076
#define tiles_level2SGBPal3c1 8935
#define tiles_level2SGBPal3c2 6596
#define tiles_level2SGBPal3c3 5344

/* Gameboy Color palette 0 */
#define tiles_level2CGBPal0c0 32767
#define tiles_level2CGBPal0c1 15855
#define tiles_level2CGBPal0c2 5285
#define tiles_level2CGBPal0c3 0

/* Gameboy Color palette 1 */
#define tiles_level2CGBPal1c0 32767
#define tiles_level2CGBPal1c1 6339
#define tiles_level2CGBPal1c2 25664
#define tiles_level2CGBPal1c3 0

/* Gameboy Color palette 2 */
#define tiles_level2CGBPal2c0 32767
#define tiles_level2CGBPal2c1 6339
#define tiles_level2CGBPal2c2 29919
#define tiles_level2CGBPal2c3 0

/* Gameboy Color palette 3 */
#define tiles_level2CGBPal3c0 31513
#define tiles_level2CGBPal3c1 32239
#define tiles_level2CGBPal3c2 19654
#define tiles_level2CGBPal3c3 0

/* Gameboy Color palette 4 */
#define tiles_level2CGBPal4c0 2847
#define tiles_level2CGBPal4c1 6339
#define tiles_level2CGBPal4c2 15855
#define tiles_level2CGBPal4c3 0

/* Gameboy Color palette 5 */
#define tiles_level2CGBPal5c0 32767
#define tiles_level2CGBPal5c1 6339
#define tiles_level2CGBPal5c2 81
#define tiles_level2CGBPal5c3 0

/* Gameboy Color palette 6 */
#define tiles_level2CGBPal6c0 32767
#define tiles_level2CGBPal6c1 13288
#define tiles_level2CGBPal6c2 8641
#define tiles_level2CGBPal6c3 0

/* Gameboy Color palette 7 */
#define tiles_level2CGBPal7c0 32767
#define tiles_level2CGBPal7c1 6339
#define tiles_level2CGBPal7c2 704
#define tiles_level2CGBPal7c3 0
/* CGBpalette entries. */
extern unsigned char tiles_level2CGB[];
/* Start of tile array. */
extern unsigned char tiles_level2[];

/* End of TILES_LEVEL2.H */
