/*

 VEHICLE.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 16 x 16
  Tiles                : 0 to 3

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define vehicleBank 0

/* Super Gameboy palette 0 */
#define vehicleSGBPal0c0 6076
#define vehicleSGBPal0c1 8935
#define vehicleSGBPal0c2 6596
#define vehicleSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define vehicleSGBPal1c0 6076
#define vehicleSGBPal1c1 8935
#define vehicleSGBPal1c2 6596
#define vehicleSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define vehicleSGBPal2c0 6076
#define vehicleSGBPal2c1 8935
#define vehicleSGBPal2c2 6596
#define vehicleSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define vehicleSGBPal3c0 6076
#define vehicleSGBPal3c1 8935
#define vehicleSGBPal3c2 6596
#define vehicleSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define vehicleCGBPal0c0 32035
#define vehicleCGBPal0c1 18384
#define vehicleCGBPal0c2 2305
#define vehicleCGBPal0c3 0

/* Gameboy Color palette 1 */
#define vehicleCGBPal1c0 10111
#define vehicleCGBPal1c1 337
#define vehicleCGBPal1c2 2305
#define vehicleCGBPal1c3 0

/* Gameboy Color palette 2 */
#define vehicleCGBPal2c0 32035
#define vehicleCGBPal2c1 337
#define vehicleCGBPal2c2 2305
#define vehicleCGBPal2c3 0

/* Gameboy Color palette 3 */
#define vehicleCGBPal3c0 32035
#define vehicleCGBPal3c1 32767
#define vehicleCGBPal3c2 7399
#define vehicleCGBPal3c3 0

/* Gameboy Color palette 4 */
#define vehicleCGBPal4c0 32733
#define vehicleCGBPal4c1 32617
#define vehicleCGBPal4c2 23008
#define vehicleCGBPal4c3 0

/* Gameboy Color palette 5 */
#define vehicleCGBPal5c0 32035
#define vehicleCGBPal5c1 9695
#define vehicleCGBPal5c2 118
#define vehicleCGBPal5c3 0

/* Gameboy Color palette 6 */
#define vehicleCGBPal6c0 32035
#define vehicleCGBPal6c1 31262
#define vehicleCGBPal6c2 22553
#define vehicleCGBPal6c3 0

/* Gameboy Color palette 7 */
#define vehicleCGBPal7c0 32767
#define vehicleCGBPal7c1 32613
#define vehicleCGBPal7c2 7399
#define vehicleCGBPal7c3 0
/* CGBpalette entries. */
extern unsigned char vehicleCGB[];
/* Start of tile array. */
extern unsigned char vehicle[];

/* End of VEHICLE.H */
