/*

 SRC/VILLAGE_MILL.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 32 x 32
  Tiles                : 0 to 7

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define village_millBank 0

/* Super Gameboy palette 0 */
#define village_millSGBPal0c0 6076
#define village_millSGBPal0c1 8935
#define village_millSGBPal0c2 6596
#define village_millSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define village_millSGBPal1c0 6076
#define village_millSGBPal1c1 8935
#define village_millSGBPal1c2 6596
#define village_millSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define village_millSGBPal2c0 6076
#define village_millSGBPal2c1 8935
#define village_millSGBPal2c2 6596
#define village_millSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define village_millSGBPal3c0 6076
#define village_millSGBPal3c1 8935
#define village_millSGBPal3c2 6596
#define village_millSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define village_millCGBPal0c0 32557
#define village_millCGBPal0c1 32767
#define village_millCGBPal0c2 5791
#define village_millCGBPal0c3 0

/* Gameboy Color palette 1 */
#define village_millCGBPal1c0 32767
#define village_millCGBPal1c1 22197
#define village_millCGBPal1c2 11627
#define village_millCGBPal1c3 0

/* Gameboy Color palette 2 */
#define village_millCGBPal2c0 32557
#define village_millCGBPal2c1 32767
#define village_millCGBPal2c2 223
#define village_millCGBPal2c3 0

/* Gameboy Color palette 3 */
#define village_millCGBPal3c0 32557
#define village_millCGBPal3c1 403
#define village_millCGBPal3c2 23872
#define village_millCGBPal3c3 0

/* Gameboy Color palette 4 */
#define village_millCGBPal4c0 32557
#define village_millCGBPal4c1 403
#define village_millCGBPal4c2 253
#define village_millCGBPal4c3 0

/* Gameboy Color palette 5 */
#define village_millCGBPal5c0 32557
#define village_millCGBPal5c1 801
#define village_millCGBPal5c2 12684
#define village_millCGBPal5c3 0

/* Gameboy Color palette 6 */
#define village_millCGBPal6c0 32557
#define village_millCGBPal6c1 7039
#define village_millCGBPal6c2 307
#define village_millCGBPal6c3 0

/* Gameboy Color palette 7 */
#define village_millCGBPal7c0 6076
#define village_millCGBPal7c1 8935
#define village_millCGBPal7c2 6596
#define village_millCGBPal7c3 5344
/* CGBpalette entries. */
extern unsigned char village_millCGB[];
/* Start of tile array. */
extern unsigned char village_mill[];

/* End of SRC/VILLAGE_MILL.H */
